export const pt = [
  'Entrar',
  'Filmes, séries e muito mais. Sem limites.',
  'Assista onde quiser. Cancele quando quiser.',
  'Pronto para assistir? Informe seu email para criar ou reiniciar sua assinatura.',
  'Vamos lá >',
  'Aproveite na TV.',
  'Assista em Smart TVs, PlayStation, Xbox, Chromecast, Apple TV, aparelhos de Blu-ray e outros dispositivos.',
  'Baixe séries para assistir offline.',
  'Salve seus títulos favoritos e sempre tenha algo para assistir.',
  'Assista quando quiser.',
  'Assista no celular, tablet, Smart TV ou notebook sem pagar a mais por isso.',
  'Crie perfis para crianças.',
  'Deixe as crianças se aventurarem com seus personagens favoritos em um espaço feito só para elas, sem pagar a mais por isso.',
  'Perguntas frequentes',
  'O que é a Netflix?',
  'A Netflix é um serviço de transmissão online que oferece uma ampla variedade de séries, filmes e documentários premiados em milhares de aparelhos conectados à internet. Você pode assistir a quantos filmes e séries quiser, quando e onde quiser, sem comerciais – tudo por um preço mensal bem acessível. Aqui você sempre encontra novidades. A cada semana, adicionamos novas séries e filmes.',
  'Quanto custa a Netflix?*',
  'Assista à Netflix no seu celular, tablet, Smart TV, notebook ou aparelho de streaming por uma taxa mensal única. Os planos variam de R$25,90 a R$55,90 por mês. Sem contrato nem taxas extras.',
  'Onde posso assistir?',
  'Assista onde quiser, quando quiser. Faça login com sua conta Netflix em netflix.com para começar a assistir no computador ou em qualquer aparelho conectado à Internet compatível com o aplicativo Netflix, como Smart TVs, smartphones, tablets, aparelhos de streaming e videogames. Você também pode baixar a sua série favorita com o aplicativo Netflix para iOS, Android ou Windows 10. Use downloads para levar a Netflix para onde quiser sem precisar de conexão com a Internet. Leve a Netflix com você para qualquer lugar.',
  'Como faço para cancelar?',
  'A Netflix é flexível. Não há contratos nem compromissos. Você pode cancelar a sua conta na internet com apenas dois cliques. Não há taxa de cancelamento – você pode começar ou encerrar a sua assinatura a qualquer momento.',
  'O que eu posso assistir na Netflix?',
  'A Netflix tem um grande catálogo de filmes, documentários, séries, originais Netflix premiados e muito mais. Assista o quanto quiser, quando quiser.',
  'A Netflix é adequada para crianças?',
  'A experiência infantil da Netflix faz parte da sua assinatura para que as crianças se divirtam em seu próprio espaço com séries e filmes familiares sob a supervisão dos pais. O recurso de controle dos pais, incluso nos perfis para crianças e protegido por PIN, permite restringir a classificação etária do conteúdo que as crianças podem ver e bloquear títulos específicos que você não quer que elas assistam.',
  'Pronto para assistir? Informe seu email para criar ou reiniciar sua assinatura.',
  'Vamos lá >',
  'Dúvidas? Ligue 0800-761-4631',
  'Perguntas frequentes',
  'Centro de ajuda',
  'Conta',
  'Media Center',
  'Relações com investidores',
  'Carreiras',
  'Resgatar cartão pré-pago',
  'Comprar cartão pré-pago',
  'Formas de assistir',
  'Termos de uso',
  'Privacidade',
  'Preferências de cookies',
  'Informações corporativas',
  'Entre em contato',
  'Teste de velocidade',
  'Avisos legais',
  'Só na Netflix',
  'Netflix Brasil - ladeia.dev.br'
]

export const en = [
  'Sing in',
  'Unlimited movies, TV shows, and more.',
  'Watch anywhere. Cancel anytime.',
  'Ready to watch? Enter your email to create or restart your membership.',
  'Get started >',
  'Enjoy on your TV.',
  'Watch on Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players, and more.',
  'Download your shows to watch offline.',
  'Save your favorites easily and always have something to watch.',
  'Watch everywhere.',
  'Stream unlimited movies and TV shows on your phone, tablet, laptop, and TV without paying more.',
  'Create profiles for kids.',
  'Send kids on adventures with their favorite characters in a space made just for them free with your membership.',
  'Frequently Asked Questions',
  'What is Netflix?',
  'Netflix is a streaming service that offers a wide variety of award-winning TV shows, movies, anime, documentaries, and more on thousands of internet-connected devices. You can watch as much as you want, whenever you want without a single commercial – all for one low monthly price. Theres always something new to discover and new TV shows and movies are added every week!',
  'How much does Netflix cost?',
  'Watch Netflix on your smartphone, tablet, Smart TV, laptop, or streaming device, all for one fixed monthly fee. Plans range from BRL25.90 to BRL55.90 a month. No extra costs, no contracts.',
  'Where can I watch?',
  'Watch anywhere, anytime. Sign in with your Netflix account to watch instantly on the web at netflix.com from your personal computer or on any internet-connected device that offers the Netflix app, including smart TVs, smartphones, tablets, streaming media players and game consoles. You can also download your favorite shows with the iOS, Android, or Windows 10 app. Use downloads to watch while you are on the go and without an internet connection. Take Netflix with you anywhere.',
  'How do I cancel?',
  'Netflix is flexible. There are no pesky contracts and no commitments. You can easily cancel your account online in two clicks. There are no cancellation fees – start or stop your account anytime.',
  'What can I watch on Netflix?',
  'Netflix has an extensive library of feature films, documentaries, TV shows, anime, award-winning Netflix originals, and more. Watch as much as you want, anytime you want.',
  'Is Netflix good for kids?',
  'The Netflix Kids experience is included in your membership to give parents control while kids enjoy family-friendly TV shows and movies in their own space. Kids profiles come with PIN-protected parental controls that let you restrict the maturity rating of content kids can watch and block specific titles you dont want kids to see.',
  'Ready to watch? Enter your email to create or restart your membership.',
  'Get started >',
  'Questions? Call 0800-761-4632',
  'FAQ',
  'Help Center',
  'Account',
  'Media Center',
  'Investor Relations',
  'Jobs',
  'Redeem Gift Cards',
  'Buy Gift Cards',
  'Ways to Watch',
  'Terms of Use',
  'Privacy',
  'Cookie Preferences',
  'Corporate Information',
  'Contact Us',
  'Speed Test',
  'Legal Notices',
  'Only on Netflix',
  'Netflix Brazil - ladeia.dev.br'
]